name: wassiet
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^4.2.1
  build_runner: ^2.2.0
  auto_route_generator: ^4.2.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.1+1
  flutter_verification_code: ^1.1.3+1
  carousel_images: ^1.1.2
  screen_utils: ^0.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_keyboard_visibility: ^5.3.0
  flutter_mobx: ^2.0.6+1
  mobx_codegen: ^2.0.7
  mobx: ^2.0.7+5
  pin_code_fields: ^7.4.0
  permission_handler: ^10.0.0
  image_picker: ^0.8.5+3
  im_stepper: ^1.0.1+1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/fake_data/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
          weight: 800

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
flutter_intl:
  enabled: true
